// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVqJ4MrkQnYOz3vZZZKfLGJOKhEMCMqMo',
    appId: '1:234567890123:web:abcdefghijklmnop',
    messagingSenderId: '234567890123',
    projectId: 'freshpunk-48db1',
    authDomain: 'freshpunk-48db1.firebaseapp.com',
    storageBucket: 'freshpunk-48db1.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqJ4MrkQnYOz3vZZZKfLGJOKhEMCMqMo',
    appId: '1:234567890123:android:abcdefghijklmnop',
    messagingSenderId: '234567890123',
    projectId: 'freshpunk-48db1',
    storageBucket: 'freshpunk-48db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVqJ4MrkQnYOz3vZZZKfLGJOKhEMCMqMo',
    appId: '1:234567890123:ios:abcdefghijklmnop',
    messagingSenderId: '234567890123',
    projectId: 'freshpunk-48db1',
    storageBucket: 'freshpunk-48db1.appspot.com',
    iosBundleId: 'com.freshpunk.freshpunk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVqJ4MrkQnYOz3vZZZKfLGJOKhEMCMqMo',
    appId: '1:234567890123:macos:abcdefghijklmnop',
    messagingSenderId: '234567890123',
    projectId: 'freshpunk-48db1',
    storageBucket: 'freshpunk-48db1.appspot.com',
    iosBundleId: 'com.freshpunk.freshpunk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVqJ4MrkQnYOz3vZZZKfLGJOKhEMCMqMo',
    appId: '1:234567890123:web:abcdefghijklmnop',
    messagingSenderId: '234567890123',
    projectId: 'freshpunk-48db1',
    authDomain: 'freshpunk-48db1.firebaseapp.com',
    storageBucket: 'freshpunk-48db1.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}