// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFeughLAfJ3THhLWVnxLqvvf2mjomkGxg',
    appId: '1:433852717304:web:318fdb802f7ff7f7c0c30d',
    messagingSenderId: '433852717304',
    projectId: 'freshpunk-48db1',
    authDomain: 'freshpunk-48db1.firebaseapp.com',
    storageBucket: 'freshpunk-48db1.firebasestorage.app',
    measurementId: 'G-11FZ3EQS7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimaxeeZSfAl5Rp1bqP3x9G6dcQWJ8thE',
    appId: '1:433852717304:android:aa920e65bae76c5fc0c30d',
    messagingSenderId: '433852717304',
    projectId: 'freshpunk-48db1',
    storageBucket: 'freshpunk-48db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cpvMjyWUXcXfiqNv0ZpavDBgxmLV9x4',
    appId: '1:433852717304:ios:7d8efe18144cb9f6c0c30d',
    messagingSenderId: '433852717304',
    projectId: 'freshpunk-48db1',
    storageBucket: 'freshpunk-48db1.firebasestorage.app',
    iosClientId: '433852717304-p815a2ucaro6nfatcuqio7qcgp8gu1jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9cpvMjyWUXcXfiqNv0ZpavDBgxmLV9x4',
    appId: '1:433852717304:ios:7d8efe18144cb9f6c0c30d',
    messagingSenderId: '433852717304',
    projectId: 'freshpunk-48db1',
    storageBucket: 'freshpunk-48db1.firebasestorage.app',
    iosClientId: '433852717304-p815a2ucaro6nfatcuqio7qcgp8gu1jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFeughLAfJ3THhLWVnxLqvvf2mjomkGxg',
    appId: '1:433852717304:web:6aaa448afbe20548c0c30d',
    messagingSenderId: '433852717304',
    projectId: 'freshpunk-48db1',
    authDomain: 'freshpunk-48db1.firebaseapp.com',
    storageBucket: 'freshpunk-48db1.firebasestorage.app',
    measurementId: 'G-FRZ5WV83ZL',
  );
}
